# GoReleaser configuration for go-pre-commit
# See: https://goreleaser.com
project_name: pre-commit

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- id: pre-commit
  binary: pre-commit
  main: ./cmd/pre-commit
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  goarm:
  - "6"
  - "7"
  ignore:
  - goos: windows
    goarch: arm64
  ldflags:
  - -s -w
  - -X main.version={{.Version}}
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X main.builtBy=goreleaser

archives:
- id: default
  format: tar.gz
  # this name template makes the OS and Arch compatible with the results of uname.
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## go-pre-commit {{ .Tag }} ({{ .Date }})

    Welcome to this new release!

  footer: |
    ## Docker Images

    - `ghcr.io/go-pre-commit/pre-commit:{{ .Tag }}`
    - `ghcr.io/go-pre-commit/pre-commit:latest`

  extra_files:
  - glob: ./README.md
  - glob: ./docs/*.md
