package commands

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/blairham/go-pre-commit/pkg/config"
)

// HookIdentifier is used to identify hook files we install
// This mirrors Python's approach of using a unique hash to identify scripts
const HookIdentifier = "# File generated by pre-commit: https://pre-commit.com"

// CurrentHash is the current hash used to identify our hook scripts
// This matches Python's CURRENT_HASH value for compatibility
const CurrentHash = "138fd403232d2ddd5efb44317e38bf03"

// PriorHashes are previous hash values used in older versions
// This matches Python's PRIOR_HASHES for backwards compatibility
var PriorHashes = []string{
	"4d9958c90bc262f47553e2c073f14cfe",
	"d8ee923c46731b42cd95cc869add4062",
	"49fd668cb42069aa1b6048464be5d395",
	"79f09a650522a87b0da915d0d983b2de",
	"e358c9dae00eac5d06b38dfdb1e33a8c",
	"go-pre-commit-v1", // Our previous identifier
}

// HookInstallOptions contains options for installing hooks
// This struct is shared between install and init-templatedir commands
type HookInstallOptions struct {
	// Config is the path to the pre-commit config file
	Config string

	// HookTypes is the list of hook types to install
	HookTypes []string

	// GitDir is the directory to install hooks into (e.g., ".git" or a template directory)
	// If empty, defaults to the current git repository's .git directory
	GitDir string

	// Overwrite indicates whether to overwrite existing hooks
	Overwrite bool

	// SkipOnMissingConfig indicates whether to add --skip-on-missing-config to hook scripts
	// This should be true for init-templatedir since repos may not have a config file
	SkipOnMissingConfig bool

	// AllowMissingConfig allows installation even if config file doesn't exist
	AllowMissingConfig bool
}

// HookInstaller provides shared hook installation functionality
// This mirrors Python's approach where init_templatedir delegates to install()
type HookInstaller struct{}

// NewHookInstaller creates a new HookInstaller
func NewHookInstaller() *HookInstaller {
	return &HookInstaller{}
}

// Install installs hooks based on the provided options
// This is the shared implementation used by both install and init-templatedir commands
func (h *HookInstaller) Install(opts *HookInstallOptions) error {
	// Determine the hooks directory
	hooksDir := h.getHooksDir(opts.GitDir)

	// Create the hooks directory
	if err := os.MkdirAll(hooksDir, 0o750); err != nil {
		return fmt.Errorf("error creating hooks directory: %w", err)
	}

	// Check if config file exists (unless we allow missing config)
	if !opts.AllowMissingConfig {
		if _, err := os.Stat(opts.Config); os.IsNotExist(err) {
			return fmt.Errorf("config file not found: %s", opts.Config)
		}
	}

	// Determine hook types: use provided ones, or get from config, or default to ["pre-commit"]
	// This matches Python's _hook_types() behavior
	hookTypes := h.getHookTypes(opts.Config, opts.HookTypes)

	// Install each hook type
	for _, hookType := range hookTypes {
		if err := h.installHook(hooksDir, hookType, opts); err != nil {
			return err
		}
	}

	return nil
}

// getHookTypes determines which hook types to install
// This matches Python's _hook_types() behavior:
// 1. If hook_types is explicitly provided, use those
// 2. Otherwise, try to load config and get default_install_hook_types
// 3. If config loading fails or default_install_hook_types is empty, return ["pre-commit"]
func (h *HookInstaller) getHookTypes(configPath string, providedHookTypes []string) []string {
	// If hook types are explicitly provided, use them
	if len(providedHookTypes) > 0 {
		return providedHookTypes
	}

	// Try to load config to get default_install_hook_types
	cfg, err := config.LoadConfig(configPath)
	if err != nil {
		// If config is invalid or doesn't exist, fallback to pre-commit (matching Python)
		return []string{"pre-commit"}
	}

	// Return default_install_hook_types from config
	// If not specified in config, Python defaults to ['pre-commit']
	if len(cfg.DefaultInstallHookTypes) == 0 {
		return []string{"pre-commit"}
	}
	return cfg.DefaultInstallHookTypes
}

// getHooksDir returns the hooks directory path based on the git directory
func (h *HookInstaller) getHooksDir(gitDir string) string {
	if gitDir == "" {
		// Default to .git/hooks in current directory
		return filepath.Join(".git", "hooks")
	}
	// For template directories, hooks go directly under gitDir/hooks
	return filepath.Join(gitDir, "hooks")
}

// installHook installs a single hook script
// Handles legacy hooks: if an existing hook is NOT our script, it's moved to .legacy
func (h *HookInstaller) installHook(hooksDir, hookType string, opts *HookInstallOptions) error {
	hookPath := filepath.Join(hooksDir, hookType)
	legacyPath := hookPath + ".legacy"

	// Check if an existing hook exists
	if _, err := os.Stat(hookPath); err == nil {
		// Hook exists - check if it's our script
		if !h.isOurScript(hookPath) {
			// Not our script - move to legacy
			if err := os.Rename(hookPath, legacyPath); err != nil {
				return fmt.Errorf("error moving existing hook to legacy: %w", err)
			}
			fmt.Printf("Moved existing %s hook to %s\n", hookType, legacyPath)
		}
	}

	// Handle overwrite behavior for legacy files
	if opts.Overwrite {
		// If overwrite is true, delete any legacy file
		if _, err := os.Stat(legacyPath); err == nil {
			if err := os.Remove(legacyPath); err != nil {
				return fmt.Errorf("error removing legacy hook: %w", err)
			}
		}
	} else {
		// If not overwriting and legacy exists, show migration mode message
		if _, err := os.Stat(legacyPath); err == nil {
			fmt.Printf("Running in migration mode with existing hooks at %s\n", legacyPath)
			fmt.Println("Use -f to use only pre-commit.")
		}
	}

	// Generate the hook script
	script := h.generateHookScript(hookType, opts)

	// Write the hook script
	if err := os.WriteFile(hookPath, []byte(script), 0o600); err != nil {
		return fmt.Errorf("error writing hook script: %w", err)
	}

	// Make the hook script executable
	// #nosec G302 - Hook scripts need to be executable
	if err := os.Chmod(hookPath, 0o700); err != nil {
		return fmt.Errorf("error making hook script executable: %w", err)
	}

	return nil
}

// isOurScript checks if the hook file was installed by pre-commit
// This mirrors Python's is_our_script() function which checks for CURRENT_HASH or PRIOR_HASHES
func (h *HookInstaller) isOurScript(hookPath string) bool {
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return false
	}

	// Check for current hash
	if bytes.Contains(content, []byte(CurrentHash)) {
		return true
	}

	// Check for any prior hashes (backwards compatibility)
	for _, priorHash := range PriorHashes {
		if bytes.Contains(content, []byte(priorHash)) {
			return true
		}
	}

	return false
}

// generateHookScript generates the hook script content
// This mirrors Python's hook-tmpl template structure
func (h *HookInstaller) generateHookScript(hookType string, opts *HookInstallOptions) string {
	// Build the hook-impl arguments array (like Python's ARGS)
	args := fmt.Sprintf("--config=%s --hook-type=%s", opts.Config, hookType)

	// Add --skip-on-missing-config if requested (used by init-templatedir)
	if opts.SkipOnMissingConfig {
		args += " --skip-on-missing-config"
	}

	// Generate a script that mirrors Python's hook-tmpl structure:
	// 1. Uses bash for better compatibility with complex scripts
	// 2. Has identification header (like Python's hash)
	// 3. Uses HERE for hook directory (like Python)
	// 4. Falls back to pre-commit command if available
	return fmt.Sprintf(`#!/usr/bin/env bash
%s
# ID: %s
# start templated
ARGS=(hook-impl %s)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`+"`"+`pre-commit`+"`"+` not found. Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
`, HookIdentifier, CurrentHash, args)
}

// ValidHookTypes returns the list of valid hook types
func ValidHookTypes() []string {
	return []string{
		"pre-commit",
		"pre-merge-commit",
		"pre-push",
		"prepare-commit-msg",
		"commit-msg",
		"post-checkout",
		"post-commit",
		"post-merge",
		"post-rewrite",
		"pre-rebase",
		"pre-auto-gc",
	}
}

// IsValidHookType checks if a hook type is valid
func IsValidHookType(hookType string) bool {
	for _, valid := range ValidHookTypes() {
		if hookType == valid {
			return true
		}
	}
	return false
}
