package cli

import (
	"os"
	"strings"
	"testing"
)

// --- versionString tests ---

func TestVersionString_Basic(t *testing.T) {
	got := versionString(BuildInfo{})
	if got == "" {
		t.Fatal("expected non-empty version string")
	}
	if !strings.HasPrefix(got, "pre-commit ") {
		t.Errorf("expected prefix 'pre-commit ', got %q", got)
	}
}

func TestVersionString_WithBuild(t *testing.T) {
	got := versionString(BuildInfo{
		Version: "1.2.3",
		Commit:  "abc123def456",
		Date:    "2025-01-01",
	})
	if !strings.Contains(got, "build 1.2.3") {
		t.Errorf("expected build version in output, got %q", got)
	}
	// Commit should be truncated to 8 chars.
	if !strings.Contains(got, "abc123de") {
		t.Errorf("expected truncated commit in output, got %q", got)
	}
	if !strings.Contains(got, "2025-01-01") {
		t.Errorf("expected date in output, got %q", got)
	}
}

func TestVersionString_DevVersion(t *testing.T) {
	got := versionString(BuildInfo{Version: "dev"})
	if strings.Contains(got, "build") {
		t.Errorf("did not expect build info for dev version, got %q", got)
	}
}

func TestVersionString_NoneCommit(t *testing.T) {
	got := versionString(BuildInfo{Version: "1.0.0", Commit: "none"})
	if strings.Contains(got, "none") {
		t.Errorf("did not expect 'none' in output, got %q", got)
	}
}

func TestVersionString_UnknownDate(t *testing.T) {
	got := versionString(BuildInfo{Version: "1.0.0", Date: "unknown"})
	if strings.Contains(got, "unknown") {
		t.Errorf("did not expect 'unknown' in output, got %q", got)
	}
}

func TestVersionString_ShortCommit(t *testing.T) {
	got := versionString(BuildInfo{Version: "1.0.0", Commit: "abc"})
	if !strings.Contains(got, "abc") {
		t.Errorf("expected short commit in output, got %q", got)
	}
}

// --- isPreCommitHook tests ---

func TestIsPreCommitHook_Generated(t *testing.T) {
	content := "#!/bin/bash\n# File generated by pre-commit\nhook-impl --config=.pre-commit-config.yaml\n"
	if !isPreCommitHook(content) {
		t.Error("expected true for generated hook")
	}
}

func TestIsPreCommitHook_WithID(t *testing.T) {
	content := "#!/bin/bash\n# ID: pre-commit-pre-commit\npre-commit hook-impl\n"
	if !isPreCommitHook(content) {
		t.Error("expected true for hook with ID marker")
	}
}

func TestIsPreCommitHook_HookImpl(t *testing.T) {
	content := "#!/bin/bash\npre-commit hook-impl --hook-type=pre-commit\n"
	if !isPreCommitHook(content) {
		t.Error("expected true for hook-impl content")
	}
}

func TestIsPreCommitHook_NotPreCommit(t *testing.T) {
	content := "#!/bin/bash\necho 'hello world'\n"
	if isPreCommitHook(content) {
		t.Error("expected false for non-pre-commit hook")
	}
}

func TestIsPreCommitHook_Empty(t *testing.T) {
	if isPreCommitHook("") {
		t.Error("expected false for empty string")
	}
}

// --- sortedHookTypes tests ---

func TestSortedHookTypes(t *testing.T) {
	types := sortedHookTypes()
	if len(types) == 0 {
		t.Fatal("expected non-empty hook types list")
	}
	for i := 1; i < len(types); i++ {
		if types[i] < types[i-1] {
			t.Errorf("hook types not sorted: %q comes after %q", types[i], types[i-1])
		}
	}
	typeSet := make(map[string]bool)
	for _, ht := range types {
		typeSet[ht] = true
	}
	for _, expected := range []string{"pre-commit", "pre-push", "commit-msg", "post-checkout"} {
		if !typeSet[expected] {
			t.Errorf("expected hook type %q not found", expected)
		}
	}
}

// --- replaceRev tests ---

func TestReplaceRev_Simple(t *testing.T) {
	raw := "    rev: v1.0.0\n"
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "", false)
	if !strings.Contains(got, "rev: v2.0.0") {
		t.Errorf("expected 'rev: v2.0.0' in output, got %q", got)
	}
}

func TestReplaceRev_SingleQuoted(t *testing.T) {
	raw := "    rev: 'v1.0.0'\n"
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "", false)
	if !strings.Contains(got, "rev: 'v2.0.0'") {
		t.Errorf("expected quoted v2.0.0, got %q", got)
	}
}

func TestReplaceRev_DoubleQuoted(t *testing.T) {
	raw := "    rev: \"v1.0.0\"\n"
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "", false)
	if !strings.Contains(got, "rev: \"v2.0.0\"") {
		t.Errorf("expected double-quoted v2.0.0, got %q", got)
	}
}

func TestReplaceRev_Freeze(t *testing.T) {
	raw := "    rev: v1.0.0\n"
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "abc123", true)
	if !strings.Contains(got, "rev: abc123") || !strings.Contains(got, "# frozen: v2.0.0") {
		t.Errorf("expected frozen rev with commit hash, got %q", got)
	}
}

func TestReplaceRev_FreezeNoCommitHash(t *testing.T) {
	raw := "    rev: v1.0.0\n"
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "", true)
	if !strings.Contains(got, "rev: v2.0.0") {
		t.Errorf("expected v2.0.0, got %q", got)
	}
	if strings.Contains(got, "frozen") {
		t.Errorf("did not expect frozen comment without commit hash, got %q", got)
	}
}

func TestReplaceRev_StripsFrozenComment(t *testing.T) {
	raw := "    rev: abc123  # frozen: v1.0.0\n"
	got := replaceRev(raw, "abc123", "v2.0.0", "", false)
	want := "    rev: v2.0.0\n"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestReplaceRev_MultipleRepos(t *testing.T) {
	raw := `repos:
-   repo: https://github.com/example/hooks
    rev: v1.0.0
-   repo: https://github.com/other/hooks
    rev: v3.0.0
`
	got := replaceRev(raw, "v1.0.0", "v2.0.0", "", false)
	if !strings.Contains(got, "rev: v2.0.0") {
		t.Error("expected v2.0.0 in output")
	}
	if !strings.Contains(got, "rev: v3.0.0") {
		t.Error("expected v3.0.0 to remain unchanged")
	}
}

// --- splitNullTerminated tests ---

func TestSplitNullTerminated(t *testing.T) {
	got := splitNullTerminated("a\x00b\x00c\x00")
	if len(got) != 3 || got[0] != "a" || got[1] != "b" || got[2] != "c" {
		t.Errorf("unexpected result: %v", got)
	}
}

func TestSplitNullTerminated_Empty(t *testing.T) {
	got := splitNullTerminated("")
	if len(got) != 0 {
		t.Errorf("expected empty result, got %v", got)
	}
}

func TestSplitNullTerminated_NoNull(t *testing.T) {
	got := splitNullTerminated("hello")
	if len(got) != 1 || got[0] != "hello" {
		t.Errorf("expected [hello], got %v", got)
	}
}

func TestSplitNullTerminated_EmptyParts(t *testing.T) {
	got := splitNullTerminated("\x00\x00a\x00")
	if len(got) != 1 || got[0] != "a" {
		t.Errorf("expected [a], got %v", got)
	}
}

// --- splitByNull tests ---

func TestSplitByNull(t *testing.T) {
	got := splitByNull("a\x00b\x00c")
	if len(got) != 3 || got[0] != "a" || got[1] != "b" || got[2] != "c" {
		t.Errorf("unexpected result: %v", got)
	}
}

func TestSplitByNull_TrailingNull(t *testing.T) {
	got := splitByNull("a\x00b\x00")
	if len(got) != 2 || got[0] != "a" || got[1] != "b" {
		t.Errorf("unexpected result: %v", got)
	}
}

// --- isLocalPath tests ---

func TestIsLocalPath_ExistingDir(t *testing.T) {
	dir := t.TempDir()
	if !isLocalPath(dir) {
		t.Error("expected true for existing directory")
	}
}

func TestIsLocalPath_NonexistentPath(t *testing.T) {
	if isLocalPath("/nonexistent/path/that/does/not/exist") {
		t.Error("expected false for nonexistent path")
	}
}

func TestIsLocalPath_File(t *testing.T) {
	dir := t.TempDir()
	f := dir + "/file.txt"
	if err := os.WriteFile(f, []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	if isLocalPath(f) {
		t.Error("expected false for regular file")
	}
}
