package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	flags "github.com/jessevdk/go-flags"

	"github.com/blairham/go-pre-commit/v4/internal/config"
	"github.com/blairham/go-pre-commit/v4/internal/git"
	"github.com/blairham/go-pre-commit/v4/internal/hook"
	"github.com/blairham/go-pre-commit/v4/internal/output"
	"github.com/blairham/go-pre-commit/v4/internal/repository"
	"github.com/blairham/go-pre-commit/v4/internal/store"
)

// hookTemplate is the shell script template installed into .git/hooks/
const hookTemplate = `#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: %s
set -eu -o pipefail

# start templated
ARGS=(hook-impl --config=%s --hook-type=%s)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '` + "`" + `pre-commit` + "`" + ` not found. Did you forget to install it?' 1>&2
    exit 1
fi
`

// hookTypes maps short names to hook filenames.
var hookTypes = map[string]string{
	"pre-commit":         "pre-commit",
	"pre-merge-commit":   "pre-merge-commit",
	"pre-push":           "pre-push",
	"prepare-commit-msg": "prepare-commit-msg",
	"commit-msg":         "commit-msg",
	"post-checkout":      "post-checkout",
	"post-commit":        "post-commit",
	"post-merge":         "post-merge",
	"post-rewrite":       "post-rewrite",
	"pre-rebase":         "pre-rebase",
}

// InstallCommand implements the "install" command.
type InstallCommand struct {
	Meta *Meta
}

type installFlags struct {
	GlobalFlags
	HookTypes    []string `short:"t" long:"hook-type" description:"The hook type(s) to install. May be specified multiple times."`
	AllowMissing bool     `long:"allow-missing-config" description:"Allow the hook installation to succeed when no config is found."`
	Overwrite    bool     `short:"f" long:"overwrite" description:"Overwrite existing hooks."`
	InstallHooks bool     `long:"install-hooks" description:"Install hook environments for all hooks in the config."`
}

func (c *InstallCommand) Run(args []string) int {
	var opts installFlags
	_, err := flags.ParseArgs(&opts, args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	// Check for core.hooksPath.
	warnIfCoreHooksPath()

	// Determine hook types to install.
	typesToInstall := opts.HookTypes
	if len(typesToInstall) == 0 {
		// Default from config's default_install_hook_types.
		if cfg, err := config.LoadConfig(opts.Config); err == nil && len(cfg.DefaultInstallHookTypes) > 0 {
			for _, ht := range cfg.DefaultInstallHookTypes {
				typesToInstall = append(typesToInstall, string(ht))
			}
		} else {
			typesToInstall = []string{"pre-commit"}
		}
	}

	// Validate hook types.
	for _, ht := range typesToInstall {
		if _, ok := hookTypes[ht]; !ok {
			fmt.Fprintf(os.Stderr, "Error: unknown hook type: %s. Choose from: %s\n", ht, strings.Join(sortedHookTypes(), ", "))
			return 1
		}
	}

	hooksDir, err := resolveHooksDir("")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	// Warn if config is missing (but don't block installation — matches Python behavior).
	if !opts.AllowMissing {
		if _, err := os.Stat(opts.Config); os.IsNotExist(err) {
			output.Warn("config file %s not found.", opts.Config)
		}
	}

	// Make the hooks directory.
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "Error: failed to create hooks directory: %v\n", err)
		return 1
	}

	// Install each hook type.
	for _, hookType := range typesToInstall {
		hookFile := filepath.Join(hooksDir, hookType)

		// Check for existing hook.
		if !opts.Overwrite {
			if info, err := os.Stat(hookFile); err == nil && info.Size() > 0 {
				content, err := os.ReadFile(hookFile)
				if err == nil && !isPreCommitHook(string(content)) {
					// Back up the legacy hook.
					legacyFile := hookFile + ".legacy"
					if err := os.Rename(hookFile, legacyFile); err != nil {
						fmt.Fprintf(os.Stderr, "Error: existing hook %s found and cannot be backed up: %v\nuse --overwrite to replace it\n", hookFile, err)
						return 1
					}
					output.Info("Moving existing hook %s to %s", hookFile, legacyFile)
				}
			}
		}

		// Write the hook script.
		installID := "pre-commit-" + hookType
		content := fmt.Sprintf(hookTemplate, installID, opts.Config, hookType)

		if err := os.WriteFile(hookFile, []byte(content), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "Error: failed to write hook: %v\n", err)
			return 1
		}

		fmt.Printf("pre-commit installed at %s\n", hookFile)
	}

	// Install hook environments if requested.
	if opts.InstallHooks {
		if err := installAllHookEnvironments(opts.Config); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return 1
		}
	}

	return 0
}

func (c *InstallCommand) Help() string {
	return strings.TrimSpace(`
Usage: pre-commit install [options]

  Install the pre-commit script into .git/hooks/.
  By default installs a pre-commit hook. Use -t multiple times to install
  several hook types.

Options:

  -t, --hook-type=TYPE         The hook type(s) to install.
      --allow-missing-config   Allow installation when no config is found.
  -f, --overwrite              Overwrite existing hooks.
      --install-hooks          Install hook environments for all hooks.
  -c, --config=FILE            Path to alternate config file.
      --color=MODE             Whether to use color (auto, always, never).
`)
}

func (c *InstallCommand) Synopsis() string {
	return "Install the pre-commit script"
}

// UninstallCommand implements the "uninstall" command.
type UninstallCommand struct {
	Meta *Meta
}

type uninstallFlags struct {
	GlobalFlags
	HookType string `short:"t" long:"hook-type" default:"pre-commit" description:"The hook type to uninstall."`
}

func (c *UninstallCommand) Run(args []string) int {
	var opts uninstallFlags
	_, err := flags.ParseArgs(&opts, args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	hooksDir, err := resolveHooksDir("")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	hookFile := filepath.Join(hooksDir, opts.HookType)

	// Check if hook exists.
	content, err := os.ReadFile(hookFile)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Printf("%s hook not found, no action taken.\n", opts.HookType)
			return 0
		}
		fmt.Fprintf(os.Stderr, "Error: failed to read hook: %v\n", err)
		return 1
	}

	if !isPreCommitHook(string(content)) {
		fmt.Printf("%s is not a pre-commit hook, no action taken.\n", hookFile)
		return 0
	}

	if err := os.Remove(hookFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error: failed to remove hook: %v\n", err)
		return 1
	}

	// Restore legacy hook if it exists.
	legacyFile := hookFile + ".legacy"
	if _, err := os.Stat(legacyFile); err == nil {
		if err := os.Rename(legacyFile, hookFile); err == nil {
			output.Info("Restored previous hook to %s", hookFile)
		}
	}

	fmt.Printf("pre-commit uninstalled from %s\n", hookFile)
	return 0
}

func (c *UninstallCommand) Help() string {
	return strings.TrimSpace(`
Usage: pre-commit uninstall [options]

  Remove the pre-commit hook from .git/hooks/.

Options:

  -t, --hook-type=TYPE   The hook type to uninstall (default: pre-commit).
  -c, --config=FILE      Path to alternate config file.
      --color=MODE       Whether to use color (auto, always, never).
`)
}

func (c *UninstallCommand) Synopsis() string {
	return "Uninstall the pre-commit script"
}

// InstallHooksCommand implements the "install-hooks" command.
type InstallHooksCommand struct {
	Meta *Meta
}

func (c *InstallHooksCommand) Run(args []string) int {
	var opts GlobalFlags
	_, err := flags.ParseArgs(&opts, args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}

	if err := installAllHookEnvironments(opts.Config); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return 1
	}
	return 0
}

func (c *InstallHooksCommand) Help() string {
	return strings.TrimSpace(`
Usage: pre-commit install-hooks [options]

  Install hook environments for all hooks in the config.

Options:

  -c, --config=FILE   Path to alternate config file.
      --color=MODE    Whether to use color (auto, always, never).
`)
}

func (c *InstallHooksCommand) Synopsis() string {
	return "Install hook environments for all hooks in the config"
}

func installAllHookEnvironments(cfgPath string) error {
	cfg, err := config.LoadConfig(cfgPath)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	s := store.New("")

	resolver := repository.NewResolver(s, cfg)
	hooks, err := resolver.ResolveAll(context.Background(), cfg)
	if err != nil {
		return fmt.Errorf("failed to resolve hooks: %w", err)
	}

	return hook.InstallEnvironments(context.Background(), hooks)
}

func resolveHooksDir(hookDir string) (string, error) {
	if hookDir != "" {
		return hookDir, nil
	}
	return git.GetHooksDir()
}

func isPreCommitHook(content string) bool {
	return strings.Contains(content, "pre-commit") &&
		(strings.Contains(content, "# File generated by pre-commit") ||
			strings.Contains(content, "hook-impl") ||
			strings.Contains(content, "ID: pre-commit"))
}

func sortedHookTypes() []string {
	types := make([]string, 0, len(hookTypes))
	for k := range hookTypes {
		types = append(types, k)
	}
	sort.Strings(types)
	return types
}

func warnIfCoreHooksPath() {
	out, err := git.CmdOutput("config", "--get", "core.hooksPath")
	if err == nil && strings.TrimSpace(out) != "" {
		output.Warn(
			"core.hooksPath is set to %q.\n"+
				"pre-commit installs hooks to .git/hooks, but git is configured to use a "+
				"different directory.\nConsider unsetting core.hooksPath or using "+
				"--hook-dir to install to the configured path.",
			strings.TrimSpace(out),
		)
	}
}
