name: CI/CD

# Configuration for caching optimization
env:
  GO_VERSION: "1.24"
  CACHE_VERSION: v1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.cache/mage-loot
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.work.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Install Go dependencies
      run: |
        go install gotest.tools/gotestsum@v1.12.0
        go install mvdan.cc/gofumpt@v0.7.0
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

    - name: Run tests
      run: mage test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.cache/mage-loot
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.work.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Install Go dependencies
      run: |
        go install mvdan.cc/gofumpt@v0.7.0
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

    - name: Run go vet
      run: mage quality:vet

    - name: Run linter
      run: mage quality:lint

  build:
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.cache/mage-loot
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.work.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Build
      run: mage build:binary

  release:
    runs-on: ubuntu-latest
    needs: [ test, lint, build ]
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.cache/mage-loot
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.work.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  language-integration:
    runs-on: ubuntu-latest
    needs: [ test ]
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'test-languages')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Python pre-commit
      run: pip install pre-commit

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/.cache/mage-loot
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.work.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Run language implementation tests
      run: mage test:languages

    - name: Upload language test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: language-test-results
        path: test-output/
        retention-days: 30
